cd 2017-hmis-api;git pull;cd ..;
cd housing-inventory-api;git pull;cd ..;
cd global-api;git pull;cd ..;
cd 2016-hmis-api;git pull;cd ..;
cd 2015-hmis-api;git pull;cd ..;
cd 2014-hmis-api;git pull;cd ..;
cd global-household-api;git pull;cd ..;
cd user-service-api;git pull;cd ..;
cd hmis-bulk-api;git pull;cd ..;
cd developer-service-api;git pull;cd ..;
cd client-consent-api;git pull;cd ..;
cd authorization-service-api;git pull;cd ..;
cd human-services-api;git pull;cd ..;
cd airs-resource-api;git pull;cd ..;
cd api-source;git pull;cd ..;
cd report-service-api;git pull;cd..;

cp -rf /proj/api/2017-hmis-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/2017-api.yaml
cp -rf /proj/api/2016-hmis-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/2016-api.yaml
cp -rf /proj/api/2015-hmis-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/2015-api.yaml
cp -rf /proj/api/2014-hmis-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/2014-api.yaml
cp -rf /proj/api/global-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/global-api.yaml
cp -rf /proj/api/authorization-service-api/api-markup/api.oas3.yaml /var/lib/tomcat7/webapps/hmis-api/authorization-service-api.yaml
cp -rf /proj/api/developer-service-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/developer-service-api.yaml
cp -rf /proj/api/client-consent-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/client-consent-api.yaml
cp -rf /proj/api/hmis-bulk-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/hmis-bulk-api.yaml
cp -rf /proj/api/housing-inventory-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/housing-inventory-api.yaml
cp -rf /proj/api/housing-matching-service-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/housing-matching-service-api.yaml
cp -rf /proj/api/human-services-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/human-services-api.yaml
cp -rf /proj/api/survey-service-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/survey-service-api.yaml
cp -rf /proj/api/user-service-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/user-service-api.yaml
cp -rf /proj/api/global-household-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/global-household-api.yaml
cp -rf /proj/api/report-service-api/api-markup/api.oas3.yaml  /var/lib/tomcat7/webapps/hmis-api/report-service-api.yaml
cp -rf /proj/api/api-source/* /var/lib/tomcat7/webapps/hmis-api/
